// Error messages
export const ERROR_MESSAGES = {
  UNAUTHORIZED: 'Unauthorized',
  POST_NOT_FOUND: 'Post not found',
  COMMENT_NOT_FOUND: 'Comment not found',
  NOT_AUTHORIZED: 'Not authorized',
  NOT_AUTHORIZED_EDIT: 'Not authorized to edit this post',
  NOT_AUTHORIZED_DELETE: 'Not authorized to delete this post',
  ALREADY_LIKED: 'Already liked',
  NOT_LIKED: 'Not liked',
  ALREADY_SAVED: 'Already saved',
  REASON_REQUIRED: 'Reason required',
  PARENT_COMMENT_NOT_FOUND: 'Parent comment not found',
  GET_FEED_FAILED: 'Failed to get feed',
  CREATE_POST_FAILED: 'Failed to create post',
  GET_POST_FAILED: 'Failed to get post',
  UPDATE_POST_FAILED: 'Failed to update post',
  DELETE_POST_FAILED: 'Failed to delete post',
  LIKE_POST_FAILED: 'Failed to like post',
  UNLIKE_POST_FAILED: 'Failed to unlike post',
  SHARE_POST_FAILED: 'Failed to share post',
  SAVE_POST_FAILED: 'Failed to save post',
  UNSAVE_POST_FAILED: 'Failed to unsave post',
  GET_SAVED_POSTS_FAILED: 'Failed to get saved posts',
  REPORT_POST_FAILED: 'Failed to report post',
  GET_USER_POSTS_FAILED: 'Failed to get user posts',
  GET_COMMENTS_FAILED: 'Failed to get comments',
  ADD_COMMENT_FAILED: 'Failed to add comment',
  DELETE_COMMENT_FAILED: 'Failed to delete comment',
  LIKE_COMMENT_FAILED: 'Failed to like comment',
  UNLIKE_COMMENT_FAILED: 'Failed to unlike comment',
  GET_REPLIES_FAILED: 'Failed to get replies',
} as const;

// Success messages
export const SUCCESS_MESSAGES = {
  POST_CREATED: 'Post created',
  POST_UPDATED: 'Post updated',
  POST_DELETED: 'Post deleted',
  POST_LIKED: 'Post liked',
  POST_UNLIKED: 'Post unliked',
  POST_SHARED: 'Post shared',
  POST_SAVED: 'Post saved',
  POST_UNSAVED: 'Post unsaved',
  POST_REPORTED: 'Post reported',
  COMMENT_ADDED: 'Comment added',
  COMMENT_DELETED: 'Comment deleted',
  COMMENT_LIKED: 'Comment liked',
  COMMENT_UNLIKED: 'Comment unliked',
} as const;
