server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/ptit_social_auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/

jwt:
  secret: ptit-social-network-secret-key-2024-very-secure-key
  expiration: 86400000
