// Error messages
export const ERROR_MESSAGES = {
  UNAUTHORIZED: 'Unauthorized',
  USER_NOT_FOUND: 'User not found',
  SEARCH_QUERY_REQUIRED: 'Search query required',
  AVATAR_URL_REQUIRED: 'Avatar URL required',
  COVER_URL_REQUIRED: 'Cover URL required',
  CANNOT_SELF_ACTION: 'Cannot perform this action on yourself',
  ALREADY_FRIENDS: 'Already friends',
  REQUEST_EXISTS: 'Friend request already exists',
  REQUEST_NOT_FOUND: 'Friend request not found',
  ALREADY_FOLLOWING: 'Already following',
  GET_PROFILE_FAILED: 'Failed to get profile',
  UPDATE_PROFILE_FAILED: 'Failed to update profile',
  GET_USER_FAILED: 'Failed to get user',
  SEARCH_FAILED: 'Failed to search users',
  UPLOAD_AVATAR_FAILED: 'Failed to upload avatar',
  UPLOAD_COVER_FAILED: 'Failed to upload cover',
  GET_SUGGESTIONS_FAILED: 'Failed to get suggestions',
  GET_FRIENDS_FAILED: 'Failed to get friends',
  GET_REQUESTS_FAILED: 'Failed to get friend requests',
  SEND_REQUEST_FAILED: 'Failed to send friend request',
  ACCEPT_REQUEST_FAILED: 'Failed to accept friend request',
  REJECT_REQUEST_FAILED: 'Failed to reject friend request',
  UNFRIEND_FAILED: 'Failed to unfriend',
  FOLLOW_FAILED: 'Failed to follow',
  UNFOLLOW_FAILED: 'Failed to unfollow',
  GET_FOLLOWERS_FAILED: 'Failed to get followers',
  GET_FOLLOWING_FAILED: 'Failed to get following',
  BLOCK_FAILED: 'Failed to block user',
  UNBLOCK_FAILED: 'Failed to unblock user',
  GET_BLOCKED_FAILED: 'Failed to get blocked users',
} as const;

// Success messages
export const SUCCESS_MESSAGES = {
  REQUEST_ACCEPTED: 'Friend request accepted',
  REQUEST_REJECTED: 'Friend request rejected',
  UNFRIENDED: 'Unfriended successfully',
  FOLLOWED: 'Followed successfully',
  UNFOLLOWED: 'Unfollowed successfully',
  BLOCKED: 'User blocked',
  UNBLOCKED: 'User unblocked',
} as const;
