// Vietnamese strings for PTIT Social App
export const Strings = {
  // App
  appName: 'PTIT Social',
  appSlogan: 'Kết nối sinh viên PTIT',

  // Auth
  auth: {
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    forgotPassword: 'Quên mật khẩu?',
    resetPassword: 'Đặt lại mật khẩu',
    email: 'Email',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    fullName: 'Họ và tên',
    studentId: 'Mã sinh viên',
    faculty: 'Khoa',
    class: 'Lớp',
    phone: 'Số điện thoại',
    rememberMe: 'Ghi nhớ đăng nhập',
    noAccount: 'Chưa có tài khoản?',
    hasAccount: 'Đã có tài khoản?',
    registerNow: 'Đăng ký ngay',
    loginNow: 'Đăng nhập ngay',
    orLoginWith: 'Hoặc đăng nhập với',
    welcomeBack: 'Chào mừng trở lại!',
    createAccount: 'Tạo tài khoản mới',
    verifyEmail: 'Xác minh email',
    verifyCode: 'Nhập mã xác nhận',
    sendCode: 'Gửi mã',
    resendCode: 'Gửi lại mã',
  },

  // Navigation
  nav: {
    home: 'Trang chủ',
    search: 'Tìm kiếm',
    create: 'Đăng bài',
    notifications: 'Thông báo',
    profile: 'Cá nhân',
    messages: 'Tin nhắn',
    groups: 'Nhóm',
    events: 'Sự kiện',
    settings: 'Cài đặt',
  },

  // Home Feed
  home: {
    newsFeed: 'Bảng tin',
    whatsOnYourMind: 'Bạn đang nghĩ gì?',
    createPost: 'Tạo bài viết',
    photo: 'Ảnh',
    video: 'Video',
    feeling: 'Cảm xúc',
    location: 'Vị trí',
    tagPeople: 'Gắn thẻ người khác',
    share: 'Chia sẻ',
    noMorePosts: 'Không còn bài viết nào',
    pullToRefresh: 'Kéo để làm mới',
  },

  // Post
  post: {
    like: 'Thích',
    comment: 'Bình luận',
    share: 'Chia sẻ',
    likes: 'lượt thích',
    comments: 'bình luận',
    shares: 'lượt chia sẻ',
    writeComment: 'Viết bình luận...',
    reply: 'Trả lời',
    viewMoreComments: 'Xem thêm bình luận',
    edit: 'Chỉnh sửa',
    delete: 'Xóa',
    report: 'Báo cáo',
    savePost: 'Lưu bài viết',
    hidePost: 'Ẩn bài viết',
    copyLink: 'Sao chép liên kết',
    public: 'Công khai',
    followers: 'Người theo dõi',
    private: 'Chỉ mình tôi',
  },

  // Profile
  profile: {
    editProfile: 'Chỉnh sửa',
    myPosts: 'Bài viết',
    myPhotos: 'Ảnh',
    myFollowers: 'Người theo dõi',
    about: 'Giới thiệu',
    bio: 'Tiểu sử',
    work: 'Công việc',
    education: 'Học vấn',
    currentCity: 'Thành phố hiện tại',
    hometown: 'Quê quán',
    relationship: 'Mối quan hệ',
    birthday: 'Sinh nhật',
    follow: 'Theo dõi',
    unfollow: 'Bỏ theo dõi',
    message: 'Nhắn tin',
    followers: 'người theo dõi',
    following: 'đang theo dõi',
    posts: 'bài viết',
    changeCover: 'Đổi ảnh bìa',
    changeAvatar: 'Đổi ảnh đại diện',
  },

  // Chat
  chat: {
    newMessage: 'Tin nhắn mới',
    typeMessage: 'Nhập tin nhắn...',
    online: 'Đang hoạt động',
    offline: 'Không hoạt động',
    lastSeen: 'Hoạt động',
    ago: 'trước',
    seen: 'Đã xem',
    delivered: 'Đã gửi',
    sending: 'Đang gửi...',
    attachFile: 'Đính kèm',
    sendPhoto: 'Gửi ảnh',
    sendVideo: 'Gửi video',
    voiceMessage: 'Tin nhắn thoại',
    videoCall: 'Gọi video',
    voiceCall: 'Gọi thoại',
    createGroup: 'Tạo nhóm chat',
    groupName: 'Tên nhóm',
    addMembers: 'Thêm thành viên',
  },

  // Notifications
  notifications: {
    title: 'Thông báo',
    all: 'Tất cả',
    unread: 'Chưa đọc',
    markAllRead: 'Đánh dấu đã đọc tất cả',
    likedPost: 'đã thích bài viết của bạn',
    commentedPost: 'đã bình luận bài viết của bạn',
    sharedPost: 'đã chia sẻ bài viết của bạn',
    followed: 'đã theo dõi bạn',
    followedBack: 'đã theo dõi lại bạn',
    mentionedYou: 'đã nhắc đến bạn',
    taggedYou: 'đã gắn thẻ bạn',
  },

  // Search
  search: {
    placeholder: 'Tìm kiếm trên PTIT Social',
    recent: 'Tìm kiếm gần đây',
    clearHistory: 'Xóa lịch sử',
    people: 'Mọi người',
    posts: 'Bài viết',
    groups: 'Nhóm',
    events: 'Sự kiện',
    noResults: 'Không tìm thấy kết quả',
  },

  // Groups
  groups: {
    myGroups: 'Nhóm của bạn',
    discover: 'Khám phá',
    createGroup: 'Tạo nhóm',
    joinGroup: 'Tham gia',
    leaveGroup: 'Rời nhóm',
    members: 'thành viên',
    admin: 'Quản trị viên',
    moderator: 'Điều hành viên',
    publicGroup: 'Nhóm công khai',
    privateGroup: 'Nhóm riêng tư',
    pendingPosts: 'Bài chờ duyệt',
    groupRules: 'Quy tắc nhóm',
  },

  // Settings
  settings: {
    title: 'Cài đặt',
    account: 'Tài khoản',
    privacy: 'Quyền riêng tư',
    security: 'Bảo mật',
    notifications: 'Thông báo',
    language: 'Ngôn ngữ',
    theme: 'Giao diện',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    help: 'Trợ giúp & hỗ trợ',
    about: 'Giới thiệu',
    deleteAccount: 'Xóa tài khoản',
    changePassword: 'Đổi mật khẩu',
    twoFactor: 'Xác thực hai yếu tố',
    blockedUsers: 'Người dùng bị chặn',
  },

  // Common
  common: {
    loading: 'Đang tải...',
    error: 'Có lỗi xảy ra',
    retry: 'Thử lại',
    cancel: 'Hủy',
    save: 'Lưu',
    done: 'Xong',
    next: 'Tiếp',
    back: 'Quay lại',
    confirm: 'Xác nhận',
    delete: 'Xóa',
    edit: 'Chỉnh sửa',
    seeMore: 'Xem thêm',
    seeLess: 'Thu gọn',
    today: 'Hôm nay',
    yesterday: 'Hôm qua',
    justNow: 'Vừa xong',
    minutesAgo: 'phút trước',
    hoursAgo: 'giờ trước',
    daysAgo: 'ngày trước',
    success: 'Thành công',
    failed: 'Thất bại',
    yes: 'Có',
    no: 'Không',
  },

  // Errors
  errors: {
    networkError: 'Lỗi kết nối mạng',
    serverError: 'Lỗi máy chủ',
    invalidEmail: 'Email không hợp lệ',
    invalidPassword: 'Mật khẩu phải có ít nhất 6 ký tự',
    passwordNotMatch: 'Mật khẩu không khớp',
    requiredField: 'Trường này là bắt buộc',
    invalidStudentId: 'Mã sinh viên không hợp lệ',
    emailExists: 'Email đã được sử dụng',
    wrongCredentials: 'Email hoặc mật khẩu không đúng',
    sessionExpired: 'Phiên đăng nhập hết hạn',
  },

  // PTIT Specific
  ptit: {
    universityName: 'Học viện Công nghệ Bưu chính Viễn thông',
    shortName: 'PTIT',
    faculties: [
      'Công nghệ Thông tin',
      'Viễn thông',
      'Điện tử',
      'Kỹ thuật Điện tử và Tin học',
      'Công nghệ Đa phương tiện',
      'An toàn Thông tin',
      'Marketing',
      'Quản trị Kinh doanh',
      'Kế toán',
    ],
    campuses: ['Hà Nội', 'TP. Hồ Chí Minh'],
  },
};

export default Strings;
