export const DATING_COLORS = {
  primary: '#e83030',
  light: {
    background: '#ffffff',
    surface: '#ffffff',
    textPrimary: '#0f172a',
    textSecondary: '#475569',
    textMuted: '#94a3b8',
    border: 'rgba(232, 48, 48, 0.1)',
  },
  dark: {
    background: '#211111',
    surface: '#1e293b',
    textPrimary: '#f1f5f9',
    textSecondary: '#94a3b8',
    textMuted: '#64748b',
    border: 'rgba(232, 48, 48, 0.1)',
  },
  onboarding: {
    background: '#f8f6f6',
    stepLabel: '#9ca3af',
    progressBarInactive: '#e6dbdb',
    illustrationOverlay: 'rgba(236, 19, 19, 0.08)',
    decorCirclePrimary: 'rgba(236, 19, 19, 0.2)',
    decorCircleSecondary: 'rgba(236, 19, 19, 0.12)',
    title: '#181111',
    description: '#4b5563',
    handle: '#e5e7eb',
    buttonText: '#ffffff',
  },
  splash: {
    glowColor: 'rgba(250, 78, 87, 0.08)',
    buttonText: '#ffffff',
  },
};

export const DATING_LAYOUT = {
  spacing: {
    sm: 12,
    md: 24,
    lg: 32,
  },
  progressBar: {
    width: 40,
    height: 4,
    gap: 10,
  },
  illustration: {
    borderRadius: 20,
    decorCircleBottomSize: 96,
    decorCircleTopSize: 128,
    decorCircleOffset: 32,
  },
  handle: {
    width: 120,
    height: 5,
    borderRadius: 3,
  },
  nextButton: {
    height: 64,
    borderRadius: 999,
    paddingHorizontal: 20,
    iconMarginLeft: 8,
    iconMarginTop: 2,
    shadowOffsetY: 10,
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 6,
  },
  typography: {
    stepLabelFontSize: 11,
    stepLabelLetterSpacing: 1.5,
    titleFontSize: 26,
    titleLetterSpacing: -0.5,
    descriptionFontSize: 15,
    descriptionLineHeight: 22,
    buttonFontSize: 18,
    buttonLetterSpacing: 0.4,
  },
  splash: {
    container: {
      paddingVertical: 40,
      paddingHorizontal: 24,
    },
    centerContent: {
      marginBottom: 80,
    },
    logo: {
      glowSize: 220,
      surfacePadding: 40,
      surfaceBorderRadius: 40,
      badgeSize: 38,
      badgePosition: 24,
      badgeBorderWidth: 4,
      shadowOffsetY: 16,
      shadowOpacity: 0.15,
      shadowRadius: 32,
      elevation: 16,
    },
    header: {
      titleMaxWidth: 320,
      titleFontSize: 48,
      titleLetterSpacing: -1.5,
    },
    footer: {
      paddingBottom: 20,
      footerTextMarginTop: 28,
      footerTextFontSize: 14,
      footerTextLineHeight: 20,
      footerTextPaddingHorizontal: 16,
      buttonHeight: 60,
      buttonBorderRadius: 30,
      shadowOffsetY: 8,
      shadowOpacity: 0.25,
      shadowRadius: 16,
      elevation: 6,
      buttonFontSize: 18,
      buttonLetterSpacing: 0.5,
      iconMarginLeft: 8,
      iconMarginTop: 2,
    },
    animation: {
      duration: 800,
      delayText: 300,
      delayButton: 600,
      springDamping: 12,
      springStiffness: 90,
    },
  },
} as const;
