import {
  DATING_SPACING,
  DATING_RADIUS,
  DATING_FONT_SIZE,
  DATING_COLORS_SEMANTIC as C,
  DATING_ANIMATION,
  DATING_LAYOUT_TOKENS as L,
} from './tokens';

/** Màu sắc dating – chỉ tham chiếu tokens, không hardcode hex */
export const DATING_COLORS = {
  primary: C.primary,
  light: {
    background: C.surface,
    surface: C.surface,
    textPrimary: C.lightTextPrimary,
    textSecondary: C.lightTextSecondary,
    textMuted: C.textMuted,
    border: C.primaryBorder,
  },
  dark: {
    background: C.darkBackground,
    surface: C.darkSurface,
    textPrimary: C.darkTextPrimary,
    textSecondary: C.textMuted,
    textMuted: C.darkTextMuted,
    border: C.primaryBorder,
  },
  onboarding: {
    background: C.surfaceAlt,
    stepLabel: C.textMuted,
    progressBarInactive: C.progressInactive,
    illustrationOverlay: C.primaryOverlay,
    decorCirclePrimary: C.decorCirclePrimary,
    decorCircleSecondary: C.decorCircleSecondary,
    title: C.textPrimary,
    description: C.textDescription,
    handle: C.border,
    buttonText: C.textInverse,
  },
  splash: {
    glowColor: C.glowSplash,
    buttonText: C.textInverse,
  },
  profileSetup: {
    background: C.surface,
    headerTitle: C.textPrimary,
    stepLabel: C.textMuted,
    sectionTitle: C.textPrimary,
    sectionHint: C.textSecondary,
    photoSlotBg: C.surfaceTrack,
    photoSlotBorder: C.borderSlot,
    mainPhotoLabel: C.textSecondary,
    bioCounter: C.textMuted,
    inputBg: C.inputBg,
    inputPlaceholder: C.inputPlaceholder,
    chipSelectedBg: C.chipSelectedBg,
    chipSelectedText: C.chipSelectedText,
    chipUnselectedBg: C.chipUnselectedBg,
    chipUnselectedText: C.chipUnselectedText,
    chipUnselectedBorder: C.chipUnselectedBorder,
    bottomBarBg: C.bottomBarBg,
    bottomBarBorder: C.bottomBarBorder,
    buttonText: C.textInverse,
  },
  preferences: {
    background: C.surface,
    headerTitle: C.textPrimary,
    stepLabel: C.primary,
    sectionTitle: C.textPrimary,
    sectionHint: C.textSecondary,
    agePillBg: C.primaryLight,
    trackBg: C.trackBg,
    trackFill: C.trackFill,
    thumbBg: C.thumbBg,
    thumbBorder: C.thumbBorder,
    selectBg: C.inputBg,
    selectBorder: C.borderTransparent,
    cardBg: C.surfaceMuted,
    cardBorder: C.borderMuted,
    toggleTrack: C.toggleTrack,
    toggleThumb: C.toggleThumb,
    privacyBg: C.infoBg,
    privacyBorder: C.infoBorder,
    privacyText: C.infoText,
    privacyIcon: C.infoIcon,
    chipBg: C.chipSelectedBg,
    chipText: C.chipSelectedText,
    buttonText: C.textInverse,
  },
  profileDetail: {
    background: C.surface,
    headerBtnBg: C.detailHeaderBtnBg,
    headerIcon: C.detailHeaderIcon,
    name: C.textPrimary,
    verified: C.detailVerified,
    locationIcon: C.detailLocationIcon,
    locationText: C.detailLocationText,
    infoCardBg: C.detailInfoCardBg,
    infoCardBorder: C.detailInfoCardBorder,
    infoCardLabel: C.detailInfoCardLabel,
    infoCardValue: C.detailInfoCardValue,
    infoCardIconBg: C.detailInfoCardIcon,
    infoCardIconColor: C.detailInfoCardIconColor,
    sectionTitle: C.detailSectionTitle,
    sectionIcon: C.detailSectionIcon,
    bioText: C.detailBioText,
    chipBg: C.detailChipBg,
    chipText: C.detailChipText,
    chipBorder: C.detailChipBorder,
    campusBg: C.detailCampusBg,
    campusBorder: C.detailCampusBorder,
    campusIcon: C.detailCampusIcon,
    campusTitle: C.detailCampusTitle,
    campusBody: C.detailCampusBody,
    divider: C.detailDivider,
    actionBarBg: C.detailActionBarBg,
    skipBtnBg: C.skipBtnBg,
    skipBtnBorder: C.border,
    skipIcon: C.skipIconColor,
    likeBtnBg: C.primary,
    likeBtnShadow: C.primaryShadow,
    likeIcon: C.textInverse,
  },
  discovery: {
    background: C.surfaceAlt,
    headerBg: C.surface,
    headerIconBg: C.surfaceAlt,
    title: C.primary,
    subtitleColor: C.textPrimary,
    cardBorder: C.border,
    gradientColors: [C.cardOverlayTop, C.cardOverlayMid, C.cardOverlayBottom],
    nameText: C.cardNameText,
    majorText: C.cardMajorText,
    bioText: C.cardBioText,
    tagBg: C.tagBg,
    tagText: C.tagText,
    infoBtnBg: C.infoBtnBg,
    infoBtnBorder: C.infoBtnBorder,
    skipBtnBg: C.skipBtnBg,
    skipBtnBorder: C.border,
    skipIcon: C.skipIconColor,
    starBtnBg: C.primary,
    starBtnShadow: C.primaryShadow,
    starIcon: C.textInverse,
    boltBtnBg: C.skipBtnBg,
    boltBtnBorder: C.border,
    boltIcon: C.boltIconColor,
    navBg: C.bottomBarBg,
    navBorder: C.borderMuted,
    navActive: C.navActive,
    navInactive: C.navInactive,
    emptyTitle: C.emptyTitleColor,
    emptySubtitle: C.emptySubtitleColor,
    matchOverlayBg: C.matchOverlayBg,
    matchText: C.matchText,
  },
};

/** Layout chỉ tham chiếu tokens (DATING_LAYOUT_TOKENS + spacing/radius/typography) */
export const DATING_LAYOUT = {
  spacing: {
    sm: DATING_SPACING.md,
    md: DATING_SPACING.xl,
    lg: DATING_SPACING.xxl,
  },
  progressBar: {
    width: L.progressBar.width,
    height: L.progressBar.height,
    gap: DATING_SPACING.sm,
  },
  onboardingStepHeader: {
    paddingHorizontal: DATING_SPACING.xl,
    paddingTop: DATING_SPACING.huge,
    paddingBottom: DATING_SPACING.lg,
    stepLabelFontSize: DATING_FONT_SIZE.small,
    stepLabelLetterSpacing: L.stepLabelLetterSpacing,
    titleFontSize: DATING_FONT_SIZE.titleLarge,
    titleFontSizeLarge: DATING_FONT_SIZE.display,
    progressBarHeight: L.progressBar.heightHeader,
    progressBarBorderRadius: DATING_RADIUS.full,
    rowMarginBottom: DATING_SPACING.xl,
    backBtnPadding: DATING_SPACING.xs,
    titleMarginTop: DATING_SPACING.xs,
    backIconSize: L.backIconSize,
    placeholderWidth: L.placeholderWidth,
    centerPaddingHorizontal: DATING_SPACING.lg,
  },
  illustration: {
    borderRadius: DATING_RADIUS.lg,
    decorCircleBottomSize: L.decorCircleBottom,
    decorCircleTopSize: L.decorCircleTop,
    decorCircleOffset: DATING_SPACING.xxl,
  },
  handle: {
    width: L.handleWidth,
    height: L.handleHeight,
    borderRadius: DATING_RADIUS.xs,
  },
  nextButton: {
    height: L.nextButtonHeight,
    borderRadius: DATING_RADIUS.full,
    paddingHorizontal: DATING_SPACING.xl,
    iconMarginLeft: DATING_SPACING.sm,
    iconMarginTop: DATING_SPACING.xs,
    shadowOffsetY: L.shadowOffsetY,
    shadowOpacity: L.shadowOpacity,
    shadowRadius: L.shadowRadius,
    elevation: L.elevation,
  },
  typography: {
    stepLabelFontSize: DATING_FONT_SIZE.caption,
    stepLabelLetterSpacing: 1.5,
    titleFontSize: DATING_FONT_SIZE.display,
    titleLetterSpacing: L.titleLetterSpacing,
    descriptionFontSize: DATING_FONT_SIZE.body,
    descriptionLineHeight: L.descriptionLineHeight,
    buttonFontSize: DATING_FONT_SIZE.title,
    buttonLetterSpacing: L.buttonLetterSpacing,
  },
  splash: {
    container: {
      paddingVertical: DATING_SPACING.xxxl,
      paddingHorizontal: DATING_SPACING.xl,
    },
    centerContent: {
      marginBottom: L.centerContentMarginBottom,
    },
    logo: {
      glowSize: L.logoGlowSize,
      surfacePadding: DATING_SPACING.xxxl,
      surfaceBorderRadius: DATING_RADIUS.xxl,
      badgeSize: L.badgeSize,
      badgePosition: DATING_SPACING.xl,
      badgeBorderWidth: DATING_SPACING.xs,
      shadowOffsetY: DATING_SPACING.lg,
      shadowOpacity: L.shadowOpacityLight,
      shadowRadius: DATING_SPACING.xxl,
      elevation: L.elevationLogo,
    },
    header: {
      titleMaxWidth: L.titleMaxWidth,
      titleFontSize: DATING_FONT_SIZE.hero,
      titleLetterSpacing: L.titleLetterSpacingHero,
    },
    footer: {
      paddingBottom: DATING_SPACING.xl,
      footerTextMarginTop: L.footerTextMarginTop,
      footerTextFontSize: DATING_FONT_SIZE.body,
      footerTextLineHeight: L.footerTextLineHeight,
      footerTextPaddingHorizontal: DATING_SPACING.lg,
      buttonHeight: L.footerButtonHeight,
      buttonBorderRadius: L.footerButtonRadius,
      shadowOffsetY: DATING_SPACING.sm,
      shadowOpacity: L.shadowOpacity,
      shadowRadius: DATING_SPACING.lg,
      elevation: L.elevation,
      buttonFontSize: DATING_FONT_SIZE.title,
      buttonLetterSpacing: 0.5,
      iconMarginLeft: DATING_SPACING.sm,
      iconMarginTop: DATING_SPACING.xs,
    },
    animation: {
      duration: L.splashAnimationDuration,
      delayText: L.splashDelayText,
      delayButton: L.splashDelayButton,
      springDamping: DATING_ANIMATION.springDamping,
      springStiffness: DATING_ANIMATION.springStiffness,
    },
  },
  profileSetup: {
    header: {
      paddingHorizontal: DATING_SPACING.lg,
      paddingVertical: DATING_SPACING.lg,
      paddingBottom: DATING_SPACING.sm,
      titleFontSize: DATING_FONT_SIZE.title,
    },
    progress: {
      paddingHorizontal: DATING_SPACING.lg,
      paddingTop: DATING_SPACING.sm,
      paddingBottom: DATING_SPACING.lg,
      stepTitleFontSize: DATING_FONT_SIZE.bodyLarge,
      stepLabelFontSize: DATING_FONT_SIZE.small,
      barHeight: L.barHeight,
      barBorderRadius: DATING_RADIUS.full,
      stepIndex: L.stepIndexProfile,
      totalSteps: L.totalSteps,
    },
    content: {
      paddingHorizontal: DATING_SPACING.lg,
      paddingBottom: L.contentPaddingBottom,
      gap: DATING_SPACING.xl,
    },
    photos: {
      sectionGap: DATING_SPACING.md,
      sectionMarginBottom: DATING_SPACING.md,
      gridGap: DATING_SPACING.md,
      mainSlotAspectRatio: 1,
      slotBorderWidth: L.slotBorderWidth,
      slotBorderRadius: DATING_RADIUS.md,
      mainIconSize: L.mainIconSize,
      mainLabelFontSize: DATING_FONT_SIZE.small,
      smallIconSize: DATING_SPACING.xl,
      totalSlots: L.photoGrid.totalSlots,
      columns: L.photoGrid.columns,
      screenPadding: L.photoGrid.screenPadding,
      cameraIconSize: L.photoGrid.cameraIconSize,
      starIconSize: L.photoGrid.starIconSize,
      badgeSize: L.photoGrid.badgeSize,
      badgeOffset: L.photoGrid.badgeOffset,
      labelMarginTop: L.photoGrid.labelMarginTop,
      overlayBg: `rgba(0,0,0,${L.photoGrid.overlayOpacity})`,
    },
    bio: {
      sectionGap: DATING_SPACING.md,
      minHeight: L.bioMinHeight,
      padding: DATING_SPACING.lg,
      inputFontSize: DATING_FONT_SIZE.body,
      counterFontSize: DATING_FONT_SIZE.small,
      maxLength: 200,
    },
    interests: {
      sectionGap: DATING_SPACING.md,
      chipGap: DATING_SPACING.sm,
      chipPaddingVertical: DATING_SPACING.sm,
      chipPaddingHorizontal: DATING_SPACING.lg,
      chipFontSize: DATING_FONT_SIZE.body,
      chipIconSize: L.chipIconSize,
      chipBorderRadius: DATING_RADIUS.full,
    },
    bottomBar: {
      paddingHorizontal: DATING_SPACING.xl,
      paddingTop: DATING_SPACING.xl,
      paddingBottom: DATING_SPACING.lg,
      safeAreaBottom: DATING_SPACING.lg,
      buttonHeight: L.buttonHeight,
      buttonBorderRadius: DATING_RADIUS.full,
      shadowOpacity: 0.2,
      shadowRadius: L.shadowRadius,
      elevation: L.elevation,
    },
  },
  preferences: {
    header: {
      paddingHorizontal: DATING_SPACING.xl,
      paddingTop: DATING_SPACING.huge,
      paddingBottom: DATING_SPACING.lg,
      stepLabelFontSize: DATING_FONT_SIZE.small,
      titleFontSize: DATING_FONT_SIZE.titleLarge,
      progressBarHeight: L.progressBar.heightHeader,
      progressBarBorderRadius: DATING_RADIUS.full,
      rowMarginBottom: DATING_SPACING.xl,
      backBtnPadding: DATING_SPACING.xs,
      titleMarginTop: DATING_SPACING.xs,
      placeholderWidth: DATING_SPACING.xxl,
      backIconSize: L.backIconSize,
    },
    content: {
      paddingHorizontal: DATING_SPACING.xl,
      paddingBottom: DATING_SPACING.bottomSheet,
      paddingTop: DATING_SPACING.lg,
      sectionMarginBottom: DATING_SPACING.xxxl,
      introTitleFontSize: DATING_FONT_SIZE.headline,
      introTitleMarginBottom: DATING_SPACING.sm,
      introHintFontSize: DATING_FONT_SIZE.body,
    },
    ageRange: {
      labelFontSize: DATING_FONT_SIZE.bodyLarge,
      pillPaddingH: DATING_SPACING.md,
      pillPaddingV: DATING_SPACING.xs,
      pillBorderRadius: DATING_RADIUS.full,
      pillFontSize: DATING_FONT_SIZE.small,
      trackHeight: L.trackHeight,
      thumbSize: L.thumbSize,
      thumbBorderWidth: L.thumbBorderWidth,
      ageMinDefault: L.ageMinDefault,
      ageMaxDefault: L.ageMaxDefault,
      ageMaxCap: L.ageMaxCap,
      labelRowMarginBottom: DATING_SPACING.xl,
      axisLabelsMarginTop: DATING_SPACING.lg,
      axisLabelFontSize: DATING_FONT_SIZE.small,
      thumbShadowColor: C.shadow,
      thumbShadowOffsetY: L.thumbShadowOffsetY,
      thumbShadowOpacity: L.shadowOpacityLight,
      thumbShadowRadius: DATING_SPACING.xs,
      thumbElevation: L.thumbElevation,
    },
    major: {
      labelFontSize: DATING_FONT_SIZE.bodyLarge,
      labelMarginBottom: DATING_SPACING.lg,
      selectPaddingH: DATING_SPACING.lg,
      selectPaddingV: DATING_SPACING.lg,
      selectBorderRadius: DATING_RADIUS.lg,
      selectMinHeight: L.buttonHeight,
      iconLeftSize: DATING_FONT_SIZE.titleLarge,
      iconRightSize: DATING_SPACING.xl,
      iconGap: DATING_SPACING.md,
      chipGap: DATING_SPACING.sm,
      chipPaddingH: DATING_SPACING.md,
      chipPaddingV: DATING_SPACING.sm,
      chipFontSize: DATING_FONT_SIZE.small,
      chipIconSize: DATING_FONT_SIZE.body,
      chipInnerGap: L.chipInnerGap,
      chipBorderRadius: DATING_RADIUS.full,
      chipMaxWidth: L.chipMaxWidth,
      chipsMarginTop: DATING_SPACING.lg,
      removeHitSlop: DATING_SPACING.sm,
      modalRowHeight: L.modalRowHeight,
      modalRowPaddingH: DATING_SPACING.xl,
      modalTitleFontSize: DATING_FONT_SIZE.title,
      modalMaxHeight: L.modalMaxHeight,
    },
    sameYear: {
      cardPadding: DATING_SPACING.xl,
      cardBorderRadius: DATING_RADIUS.xl,
      cardMarginBottom: DATING_SPACING.huge,
      textWrapPaddingRight: DATING_SPACING.lg,
      titleFontSize: DATING_FONT_SIZE.bodyLarge,
      hintFontSize: DATING_FONT_SIZE.small,
      hintMarginTop: DATING_SPACING.xs,
      hintLineHeight: L.hintLineHeight,
    },
    privacy: {
      padding: DATING_SPACING.lg,
      borderRadius: DATING_RADIUS.lg,
      iconSize: DATING_FONT_SIZE.titleLarge,
      iconMarginTop: L.iconMarginTop,
      textFontSize: DATING_FONT_SIZE.small,
      textLineHeight: L.hintLineHeight,
      contentGap: DATING_SPACING.md,
    },
    bottomBar: {
      paddingHorizontal: DATING_SPACING.xl,
      paddingTop: DATING_SPACING.xxxl,
      paddingBottom: DATING_SPACING.xl,
      buttonHeight: L.buttonHeight,
      buttonBorderRadius: DATING_RADIUS.full,
      buttonGap: DATING_SPACING.sm,
      buttonIconSize: DATING_SPACING.xl,
      buttonFontSize: DATING_FONT_SIZE.title,
      shadowOffsetY: L.shadowOffsetYStrong,
      shadowOpacity: L.shadowOpacityStrong,
      shadowRadius: L.shadowRadiusStrong,
      elevation: L.elevationStrongBar,
      pressScaleDown: DATING_ANIMATION.pressScaleDown,
      springDamping: DATING_ANIMATION.springDampingButton,
      springStiffness: DATING_ANIMATION.springStiffnessButton,
    },
    animation: {
      entranceDuration: DATING_ANIMATION.durationEntrance,
      entranceStagger: DATING_ANIMATION.stagger,
      entranceTranslateY: DATING_ANIMATION.translateYEntrance,
      modalOverlayDuration: DATING_ANIMATION.durationFast,
      modalSheetDuration: DATING_ANIMATION.durationNormal,
      modalSheetDamping: DATING_ANIMATION.modalSheetDamping,
      modalSheetStiffness: DATING_ANIMATION.modalSheetStiffness,
    },
  },
  profileDetail: {
    image: {
      heightRatio: L.profileDetail.imageHeight,
    },
    photoGrid: {
      gap: L.profileDetail.photoGridGap,
      borderRadius: L.profileDetail.photoGridRadius,
      aspectRatio: L.profileDetail.photoGridAspectRatio,
    },
    header: {
      btnSize: L.profileDetail.headerBtnSize,
      btnRadius: L.profileDetail.headerBtnRadius,
      iconSize: L.profileDetail.headerIconSize,
      topRowGap: L.profileDetail.headerTopRowGap,
      paddingH: DATING_SPACING.lg,
      paddingTop: DATING_SPACING.md,
    },
    identity: {
      paddingH: DATING_SPACING.xl,
      paddingTop: DATING_SPACING.xl,
      nameSize: L.profileDetail.nameSize,
      verifiedSize: L.profileDetail.verifiedSize,
      locationIconSize: L.profileDetail.locationIconSize,
      locationTextSize: L.profileDetail.locationTextSize,
      locationGap: DATING_SPACING.xs,
      locationMarginTop: DATING_SPACING.sm,
    },
    infoCards: {
      sectionPaddingH: DATING_SPACING.xl,
      marginTop: DATING_SPACING.xl,
      gap: DATING_SPACING.md,
      iconSize: L.profileDetail.infoCardIconSize,
      labelSize: L.profileDetail.infoCardLabelSize,
      valueSize: L.profileDetail.infoCardValueSize,
      radius: L.profileDetail.infoCardRadius,
      cardPaddingV: L.profileDetail.infoCardPaddingV,
      cardPaddingH: L.profileDetail.infoCardPaddingH,
      iconBgSize: L.profileDetail.infoCardIconSize + DATING_SPACING.md,
    },
    section: {
      paddingH: DATING_SPACING.xl,
      marginTop: DATING_SPACING.xl,
      titleSize: L.profileDetail.sectionTitleSize,
      iconSize: L.profileDetail.sectionIconSize,
      titleGap: DATING_SPACING.sm,
      contentMarginTop: DATING_SPACING.md,
    },
    bio: {
      textSize: L.profileDetail.bioTextSize,
      lineHeight: L.profileDetail.bioLineHeight,
    },
    chips: {
      height: L.profileDetail.chipHeight,
      fontSize: L.profileDetail.chipFontSize,
      paddingH: L.profileDetail.chipPaddingH,
      borderRadius: L.profileDetail.chipBorderRadius,
      gap: DATING_SPACING.sm,
    },
    campus: {
      iconSize: L.profileDetail.campusIconSize,
      titleSize: L.profileDetail.campusTitleSize,
      bodySize: L.profileDetail.campusBodySize,
      bodyLineHeight: L.profileDetail.campusBodyLineHeight,
      radius: L.profileDetail.campusCardRadius,
      padding: DATING_SPACING.lg,
      gap: DATING_SPACING.md,
    },
    actionBar: {
      height: L.profileDetail.actionBarHeight,
      skipSize: L.profileDetail.skipBtnSize,
      skipIconSize: L.profileDetail.skipIconSize,
      likeSize: L.profileDetail.likeBtnSize,
      likeIconSize: L.profileDetail.likeIconSize,
      gap: L.profileDetail.actionGap,
    },
    divider: {
      height: L.profileDetail.dividerHeight,
      marginH: DATING_SPACING.xl,
      marginV: DATING_SPACING.xl,
    },
    scrollPaddingBottom: L.profileDetail.actionBarHeight + DATING_SPACING.xl,
  },
  discovery: {
    header: {
      paddingH: DATING_SPACING.xl,
      paddingTop: DATING_SPACING.xl,
      paddingBottom: DATING_SPACING.sm,
      iconSize: L.discovery.headerIconSize,
      titleSize: L.discovery.headerTitleSize,
      subtitleSize: L.discovery.headerSubtitleSize,
      subtitleOpacity: L.discovery.headerSubtitleOpacity,
    },
    card: {
      borderRadius: L.discovery.cardBorderRadius,
      padding: DATING_SPACING.xl,
      infoBtnSize: L.discovery.cardInfoBtnSize,
      nameSize: L.discovery.nameSize,
      majorSize: L.discovery.majorSize,
      majorIconSize: L.discovery.majorIconSize,
      bioSize: L.discovery.bioSize,
      bioLineHeight: L.discovery.bioLineHeight,
      bioMaxLines: L.discovery.bioMaxLines,
    },
    tag: {
      height: L.discovery.tagHeight,
      fontSize: L.discovery.tagFontSize,
      paddingH: L.discovery.tagPaddingH,
      iconSize: L.discovery.tagIconSize,
      borderRadius: L.discovery.tagBorderRadius,
      gap: DATING_SPACING.sm,
    },
    actions: {
      skipSize: L.discovery.skipBtnSize,
      skipIconSize: L.discovery.skipIconSize,
      starSize: L.discovery.starBtnSize,
      starIconSize: L.discovery.starIconSize,
      boltSize: L.discovery.boltBtnSize,
      boltIconSize: L.discovery.boltIconSize,
      gap: L.discovery.actionGap,
      paddingBottom: DATING_SPACING.xxl + DATING_SPACING.md,
      paddingTop: DATING_SPACING.lg,
    },
    nav: {
      iconSize: L.discovery.navIconSize,
      labelSize: L.discovery.navLabelSize,
      paddingTop: DATING_SPACING.md,
      paddingBottom: DATING_SPACING.xxl,
    },
    empty: {
      titleSize: L.discovery.emptyTitleSize,
      subtitleSize: L.discovery.emptySubtitleSize,
      subtitlePaddingH: L.discovery.emptySubtitlePaddingH,
      subtitleMarginTop: L.discovery.emptySubtitleMarginTop,
    },
    match: {
      textSize: L.discovery.matchTextSize,
      durationMs: L.discovery.matchDurationMs,
    },
    feed: {
      pageSize: L.discovery.pageSize,
      prefetchThreshold: L.discovery.prefetchThreshold,
    },
  },
} as const;
