server:
  port: 8082

spring:
  application:
    name: post-service
  datasource:
    url: jdbc:postgresql://postgres:5432/ptit_social_post
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
