/**
 * Số layout dùng chung (icon size, height, width, lineHeight, opacity…).
 * Theme chỉ tham chiếu từ đây + DATING_SPACING/DATING_RADIUS, không magic number.
 */
export const DATING_LAYOUT_TOKENS = {
  progressBar: { width: 40, height: 4, heightHeader: 6 },
  stepLabelLetterSpacing: 1,
  backIconSize: 28,
  placeholderWidth: 32,
  decorCircleBottom: 96,
  decorCircleTop: 128,
  handleWidth: 120,
  handleHeight: 5,
  nextButtonHeight: 64,
  shadowOffsetY: 10,
  shadowOpacity: 0.25,
  shadowOpacityLight: 0.15,
  shadowRadius: 20,
  elevation: 6,
  elevationStrong: 8,
  elevationLogo: 16,
  titleLetterSpacing: -0.5,
  descriptionLineHeight: 22,
  buttonLetterSpacing: 0.4,
  centerContentMarginBottom: 80,
  logoGlowSize: 220,
  badgeSize: 38,
  titleMaxWidth: 320,
  titleLetterSpacingHero: -1.5,
  footerTextMarginTop: 28,
  footerTextLineHeight: 20,
  footerButtonHeight: 60,
  footerButtonRadius: 30,
  splashAnimationDuration: 800,
  splashDelayText: 300,
  splashDelayButton: 600,
  contentPaddingBottom: 140,
  bioMinHeight: 120,
  slotBorderWidth: 2,
  mainIconSize: 40,
  chipIconSize: 18,
  modalRowHeight: 52,
  modalMaxHeight: 320,
  hintLineHeight: 18,
  iconMarginTop: 2,
  contentGap: 6,
  trackHeight: 6,
  thumbSize: 28,
  thumbBorderWidth: 2,
  ageMinDefault: 18,
  ageMaxDefault: 24,
  ageMaxCap: 30,
  chipInnerGap: 6,
  chipMaxWidth: 140,
  barHeight: 6,
  stepIndexProfile: 2,
  totalSteps: 3,
  buttonHeight: 56,
  shadowOffsetYStrong: 10,
  shadowOpacityStrong: 0.3,
  shadowRadiusStrong: 20,
  elevationStrongBar: 8,
  thumbShadowOffsetY: 2,
  thumbElevation: 4,
} as const;
