import { StyleSheet } from 'react-native';
import { DATING_COLORS } from '../../../constants/dating/theme';
import { DATING_SPACING, DATING_LAYOUT_TOKENS } from '../../../constants/dating/tokens';

const MATCH_SUCCESS_LAYOUT = {
  avatarSize: 128,
  avatarBorderWidth: 4,
  avatarOverlap: 24,
  heartSize: 56,
  heartIconSize: 32,
  titleFontSize: 36,
  titleMarginBottom: 16,
  subtitleFontSize: 18,
  subtitleLineHeight: 26,
  subtitleMarginBottom: 48,
  contentMaxWidth: 384,
  actionsGap: 16,
  actionsPaddingH: 16,
  btnHeight: 56,
  btnBorderRadius: 28,
  btnFontSize: 18,
  confettiDotSize: 1,
  confettiGridSize: 40,
  spacerHeight: 40,
  actionsMaxWidth: 448,
} as const;

const L = MATCH_SUCCESS_LAYOUT;

export const matchSuccessStyles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: DATING_COLORS.profileDetail.background,
  },
  safeArea: {
    flex: 1,
  },
  confettiOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: DATING_COLORS.primary,
    opacity: 0.15,
    pointerEvents: 'none',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: DATING_SPACING.lg,
    paddingTop: DATING_SPACING.lg,
    paddingBottom: DATING_SPACING.sm,
    zIndex: 10,
  },
  closeBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '700',
    color: DATING_COLORS.profileDetail.name,
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  headerPlaceholder: { width: 48 },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: DATING_SPACING.lg,
    zIndex: 10,
  },
  avatarSection: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 48,
  },
  avatarLeft: {
    marginRight: -L.avatarOverlap,
    zIndex: 10,
  },
  avatarRight: {
    marginLeft: -L.avatarOverlap,
    zIndex: 20,
  },
  avatar: {
    width: L.avatarSize,
    height: L.avatarSize,
    borderRadius: L.avatarSize / 2,
    borderWidth: L.avatarBorderWidth,
    borderColor: DATING_COLORS.profileDetail.background,
    overflow: 'hidden',
    backgroundColor: DATING_COLORS.preferences.cardBg,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  heartWrap: {
    zIndex: 30,
    width: L.heartSize,
    height: L.heartSize,
    borderRadius: L.heartSize / 2,
    backgroundColor: DATING_COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: L.avatarBorderWidth,
    borderColor: DATING_COLORS.profileDetail.background,
    marginHorizontal: -L.heartSize / 2,
    shadowColor: DATING_COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: DATING_LAYOUT_TOKENS.shadowOpacityLight,
    shadowRadius: DATING_SPACING.md,
    elevation: DATING_LAYOUT_TOKENS.elevation,
  },
  textBlock: {
    maxWidth: L.contentMaxWidth,
    alignItems: 'center',
    marginBottom: L.subtitleMarginBottom,
  },
  title: {
    fontSize: L.titleFontSize,
    fontWeight: '800',
    letterSpacing: -0.5,
    color: DATING_COLORS.discovery.matchTitleHighlight,
    textAlign: 'center',
    marginBottom: L.titleMarginBottom,
  },
  subtitle: {
    fontSize: L.subtitleFontSize,
    fontWeight: '500',
    lineHeight: L.subtitleLineHeight,
    color: DATING_COLORS.profileDetail.infoCardValue,
    textAlign: 'center',
  },
  actions: {
    width: '100%',
    maxWidth: L.actionsMaxWidth,
    gap: L.actionsGap,
    paddingHorizontal: L.actionsPaddingH,
  },
  primaryBtn: {
    height: L.btnHeight,
    borderRadius: L.btnBorderRadius,
    backgroundColor: DATING_COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: DATING_SPACING.sm,
    shadowColor: DATING_COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: DATING_LAYOUT_TOKENS.shadowOpacityLight,
    shadowRadius: DATING_SPACING.md,
    elevation: DATING_LAYOUT_TOKENS.elevation,
  },
  primaryBtnText: {
    fontSize: L.btnFontSize,
    fontWeight: '700',
    color: DATING_COLORS.onboarding.buttonText,
  },
  primaryBtnPressed: { opacity: 0.9 },
  secondaryBtn: {
    height: L.btnHeight,
    borderRadius: L.btnBorderRadius,
    borderWidth: 2,
    borderColor: `${DATING_COLORS.primary}33`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: {
    fontSize: L.btnFontSize,
    fontWeight: '700',
    color: DATING_COLORS.primary,
  },
  secondaryBtnPressed: { opacity: 0.9 },
  spacer: { height: L.spacerHeight },
});

export { MATCH_SUCCESS_LAYOUT };
